---
- name: Install Kubernetes Cluster with k3sup
  hosts: localhost
  become: true
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name:
          - docker.io
        state: present
        update_cache: yes

    - name: Add user to Docker group
      user:
        name: "{{ ansible_env.USER }}"
        groups: docker
        append: yes

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Download k3sup
      get_url:
        url: https://github.com/alexellis/k3sup/releases/download/0.13.8/k3sup
        dest: /usr/local/bin/k3sup
        mode: '0755'

    - name: Install K3s using k3sup
      command:
        cmd: >
          k3sup install --local \
          --user {{ ansible_env.USER }} \
          --k3s-version v1.31.5+k3s1 \
          --k3s-extra-args="--disable=traefik --docker --write-kubeconfig-mode=644" \
          --ssh-key "{{ ansible_env.HOME }}/.ssh/id_ed25519" \
          --local-path "{{ ansible_env.HOME }}/.kube/config"
      register: k3sup_output

    - name: Display k3sup output
      debug:
        var: k3sup_output.stdout_lines
