---
- name: Install Kubernetes Cluster with k3sup
  hosts: localhost
  become: true
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Install kubectl
      get_url:
        url: https://dl.k8s.io/release/v1.31.5/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Download k3sup
      get_url:
        url: https://github.com/alexellis/k3sup/releases/download/0.13.8/k3sup
        dest: /usr/local/bin/k3sup
        mode: '0755'

    - name: Install K3s using k3sup
      command:
        cmd: >
          k3sup install --local \
          --user roo \
          --k3s-version v1.31.5+k3s1 \
          --k3s-extra-args="--disable=traefik --docker --write-kubeconfig-mode=644" \
          --local-path "{{ ansible_env.HOME }}/.kube/config"
      register: k3sup_output

    - name: Display k3sup output
      debug:
        var: k3sup_output.stdout_lines
