---
- name: Install Kubernetes Cluster with k3sup
  hosts: localhost
  become: true
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
          - git
        state: present
        update_cache: yes

    - name: Download and install k3sup
      shell: |
        curl -sLS https://get.k3sup.dev | sh
        sudo install k3sup /usr/local/bin/

    - name: Install K3s using k3sup
      command:
        cmd: >
          k3sup install --local \
          --user roo \
          --k3s-version v1.31.5+k3s1 \
          --k3s-extra-args="--disable=traefik --docker --write-kubeconfig-mode=644" \
          --local-path "{{ ansible_env.HOME }}/.kube/config"
      register: k3sup_output

    - name: Display k3sup output
      debug:
        var: k3sup_output.stdout_lines
